apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort # Define o tipo do serviço como NodePort
  ports:
    - port: 80
      nodePort: 30000
  selector:
    app: primeiro-pod