apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1-loadbalancer
spec:
  type: LoadBalancer # Define o tipo do serviço como LoadBalancer
  ports: 
    - port: 80
      nodeport: 30000
  selector:
    app: primeiro-pod